Infura now requires an API key, fixes #170
Introduces `python-dotenv` to load environment variables and inject API
keys for both Etherscan and Infura.
Also bumps Pillow version and pins hostpython3 to match python3 closes #166.
Last, pins `virtualenv<20` to fix the Android build, error was:
```
Traceback (most recent call last):
  File "/home/user/.local/bin/virtualenv", line 7, in <module>
    from virtualenv import main
ImportError: cannot import name 'main
```