Fixes pyconfig_armeabi.h not found, refs #71
The problem was some `CFLAGS` were missing, most likely `-march=armv7-a`.

The error was:
```
In file included from ~/.buildozer/crystax-ndk/sources/python/3.6/include/python/Python.h:8:0,
                 from build/temp.linux-x86_64-3.6/_libsecp256k1.c:2:
~/.buildozer/crystax-ndk/sources/python/3.6/include/python/pyconfig.h:2:30:
fatal error: pyconfig_armeabi.h: No such file or directory
```